"""Add version relationship to structures and causes with named constraints

Revision ID: 8f45b8b26339
Revises: 45380083bbdd
Create Date: 2025-04-03 15:44:28.150419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f45b8b26339'
down_revision = '45380083bbdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('legal_cause', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_cause_version_id', 'legal_regulation_version', ['version_id'], ['id'])

    with op.batch_alter_table('legal_structure', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_structure_version_id', 'legal_regulation_version', ['version_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('legal_structure', schema=None) as batch_op:
        batch_op.drop_constraint('fk_structure_version_id', type_='foreignkey')
        batch_op.drop_column('version_id')

    with op.batch_alter_table('legal_cause', schema=None) as batch_op:
        batch_op.drop_constraint('fk_cause_version_id', type_='foreignkey')
        batch_op.drop_column('version_id')

    # ### end Alembic commands ###
