"""Initial migration

Revision ID: bed83cc71748
Revises: 
Create Date: 2025-04-08 14:23:41.706407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bed83cc71748'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('legal_regulation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('issuing_authority', sa.String(length=100), nullable=True),
    sa.Column('effective_date', sa.DateTime(), nullable=True),
    sa.Column('publish_date', sa.DateTime(), nullable=True),
    sa.Column('hierarchy_level', sa.String(length=50), nullable=True),
    sa.Column('validity_status', sa.String(length=50), nullable=True),
    sa.Column('province', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('original_enactment_date', sa.DateTime(), nullable=True),
    sa.Column('latest_revision_date', sa.DateTime(), nullable=True),
    sa.Column('current_version_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('legal_regulation_version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('regulation_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.String(length=50), nullable=True),
    sa.Column('revision_date', sa.DateTime(), nullable=True),
    sa.Column('effective_date', sa.DateTime(), nullable=True),
    sa.Column('publish_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('changes_summary', sa.Text(), nullable=True),
    sa.Column('step_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['regulation_id'], ['legal_regulation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('legal_cause',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('regulation_id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('violation_type', sa.String(length=200), nullable=True),
    sa.Column('violation_clause', sa.String(length=200), nullable=True),
    sa.Column('behavior', sa.Text(), nullable=True),
    sa.Column('illegal_behavior', sa.Text(), nullable=True),
    sa.Column('penalty_type', sa.String(length=200), nullable=True),
    sa.Column('penalty_clause', sa.String(length=200), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['regulation_id'], ['legal_regulation.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['legal_regulation_version.id'], name='fk_cause_version_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('legal_structure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('regulation_id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('article', sa.Integer(), nullable=True),
    sa.Column('paragraph', sa.Integer(), nullable=True),
    sa.Column('item', sa.Integer(), nullable=True),
    sa.Column('section', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('original_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['regulation_id'], ['legal_regulation.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['legal_regulation_version.id'], name='fk_structure_version_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('legal_punishment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cause_id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('circumstance', sa.String(length=200), nullable=True),
    sa.Column('punishment_type', sa.String(length=100), nullable=True),
    sa.Column('progressive_punishment', sa.String(length=200), nullable=True),
    sa.Column('industry', sa.String(length=200), nullable=True),
    sa.Column('subject_level', sa.String(length=100), nullable=True),
    sa.Column('punishment_target', sa.String(length=100), nullable=True),
    sa.Column('punishment_details', sa.Text(), nullable=True),
    sa.Column('additional_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cause_id'], ['legal_cause.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['legal_regulation_version.id'], name='fk_punishment_version_id'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('legal_punishment')
    op.drop_table('legal_structure')
    op.drop_table('legal_cause')
    op.drop_table('legal_regulation_version')
    op.drop_table('user')
    op.drop_table('legal_regulation')
    # ### end Alembic commands ###
