"""Add version_id to LegalPunishment

Revision ID: cd132054093f
Revises: 8f45b8b26339
Create Date: 2025-04-03 17:51:46.208497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd132054093f'
down_revision = '8f45b8b26339'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('legal_punishment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_punishment_version_id', 'legal_regulation_version', ['version_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('legal_punishment', schema=None) as batch_op:
        batch_op.drop_constraint('fk_punishment_version_id', type_='foreignkey')
        batch_op.drop_column('version_id')

    # ### end Alembic commands ###
