"""Add step_id field to LegalRegulation

Revision ID: cf90b5dbae42
Revises: cd132054093f
Create Date: 2025-04-04 16:19:18.819314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf90b5dbae42'
down_revision = 'cd132054093f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('legal_regulation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('step_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('legal_regulation', schema=None) as batch_op:
        batch_op.drop_column('step_id')

    # ### end Alembic commands ###
