"""Add penalty fields to legal cause

Revision ID: ff32d386e740
Revises: 5e509aab697a
Create Date: 2025-03-23 20:46:22.328714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff32d386e740'
down_revision = '5e509aab697a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('legal_cause', schema=None) as batch_op:
        batch_op.add_column(sa.Column('penalty_type', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('penalty_clause', sa.String(length=200), nullable=True))

    with op.batch_alter_table('legal_regulation', schema=None) as batch_op:
        batch_op.drop_column('industry_category')
        batch_op.drop_column('validity')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('legal_regulation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('validity', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('industry_category', sa.VARCHAR(length=100), nullable=True))

    with op.batch_alter_table('legal_cause', schema=None) as batch_op:
        batch_op.drop_column('penalty_clause')
        batch_op.drop_column('penalty_type')

    # ### end Alembic commands ###
